function dfsingleleg1rtPowers = importPowers(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  DFSINGLELEG1RTPOWERS = IMPORTFILE1(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  DFSINGLELEG1RTPOWERS = IMPORTFILE1(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  dfsingleleg1rtPowers = importfile1("C:\Users\Daniel.Feeney\Dropbox (Boa)\Hike Work Research\Data\BalanceMeasures\df single leg 1rt - Powers.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Feb-2020 10:24:23

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Sample", "Landing", "Takeoff", "LAnklePower", "RAnklePower", "RHipPower", "RKneePower", "LHipPower", "LKneePower", "COMPower", "COM_Power_Y", "COM_Power_CMJ", "L5X", "L5Y", "L5Z", "VarName16"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 16, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 16, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
dfsingleleg1rtPowers = readtable(filename, opts);

end