function dfsingleleg1rtJointMoments = importMoments(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  DFSINGLELEG1RTJOINTMOMENTS = IMPORTFILE1(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  DFSINGLELEG1RTJOINTMOMENTS = IMPORTFILE1(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  dfsingleleg1rtJointMoments = importfile1("C:\Users\Daniel.Feeney\Dropbox (Boa)\Hike Work Research\Data\BalanceMeasures\df single leg 1rt - JointMoments.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 14-Feb-2020 10:23:42

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Sample", "RightAnkleMomentSagittal", "RightAnkleMomentFrontal", "RightAnkleMomentTransverse", "RightKneeMomentSagittal", "RightKneeMomentFrontal", "RightKneeMomentTransverse", "RightHipMomentSagittal", "RightHipMomentFrontal", "RightHipMomentTransverse", "VarName11"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 11, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 11, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
dfsingleleg1rtJointMoments = readtable(filename, opts);

end