function CMJlacesTriangleForces = importForces(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CMJLACESTRIANGLEFORCES = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  CMJLACESTRIANGLEFORCES = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  CMJlacesTriangleForces = importfile("C:\Users\Daniel.Feeney\Dropbox (Boa)\TMM Files\BHtmmFiles\CMJ_laces - TriangleForces.txt", [8, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Jul-2019 16:36:42

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [8, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 18);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Sample", "ForceX3", "ForceY3", "ForceZ3", "COPx", "COPy", "ForceX1", "ForceY1", "ForceZ1", "ForceX2", "ForceY2", "ForceZ2", "ForceX4", "ForceY4", "ForceZ4", "Landing", "Takeoff", "VarName18"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 18, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 18, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
CMJlacesTriangleForces = readtable(filename, opts);

end