function cvlace1Forces = importGolfForces(filename, dataLines)
%IMPORTFILE Import data from a text file
%  CVLACE1FORCES = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  CVLACE1FORCES = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  cvlace1Forces = importfile("C:\Users\Daniel.Feeney\Dropbox (Boa)\Golf\Golf Pilot Aug 2019\AllSubjectPoints\cv lace 1 - Forces.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Sep-2019 12:43:44

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Sample", "RForceX", "RForceY", "RForceZ", "RCOPx", "RCOPy", "LForceX", "LForceY", "LForceZ", "LCOPx", "LCOPy", "frontMomentZ", "rearMomentZ", "VarName14"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 14, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 14, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
cvlace1Forces = readtable(filename, opts);

end