function PowersMomentsAngles = importKineticsKinematics(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  SUB0CMJ1POWERSMOMENTSANGLES = IMPORTFILE1(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  SUB0CMJ1POWERSMOMENTSANGLES = IMPORTFILE1(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  sub0CMJ1PowersMomentsAngles = importfile1("C:\Users\Daniel.Feeney\Dropbox (Boa)\Endurance Health Validation\DU Pilot Testing\sub0_CMJ_1 - PowersMomentsAngles.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Mar-2020 10:30:22

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 33);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Sample", "Landing", "Takeoff", "LAnklePower", "RAnklePower", "RHipPower", "RKneePower", "LHipPower", "LKneePower", "COMPower", "COM_Power_Y", "COM_Power_CMJ", "L5X", "L5Y", "L5Z", "RightAnkleMomentSagittal", "RightHipMomentFrontal", "RightHipMomentTransverse", "RightKneeMomentTransverse", "RightKneeMomentFrontal", "RightKneeMomentSaggital", "RightAnkleMomentTransverse", "RightAnkleMomentFrontal", "RightAnkleMomentSaggital", "RAnkleAbduction", "RAnkleInversion", "RAnkleDorsiflexion", "RKneeFlexion", "RKneeRotation", "RHipFlexion", "RHipAbduction", "RHipRoation", "VarName33"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 33, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 33, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
PowersMomentsAngles = readtable(filename, opts);

end