function cwx2Kinetics = importKinetics(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  CWX2KINETICS = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  CWX2KINETICS = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  cwx2Kinetics = importfile1("C:\Users\Daniel.Feeney\Dropbox (Boa)\Golf\Golf Pilot Aug 2019\AllSubjectPoints\cw x 2 - Kinetics.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Sep-2019 16:18:53

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Sample", "leftAnklePower", "rightAnklePower", "rightHipMomentX", "rightHipMomentY", "rightHipMomentZ", "leftHipMomentX", "leftHipMomentY", "leftHipMomentZ", "RightHipPower", "LeftHipPower", "VarName12"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 12, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 12, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
cwx2Kinetics = readtable(filename, opts);

end