function TriangleTestTriangleForces = importForces(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TRIANGLETESTTRIANGLEFORCES = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  TRIANGLETESTTRIANGLEFORCES = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  TriangleTestTriangleForces = importfile("C:\Users\Daniel.Feeney\Dropbox (Boa)\TMM Files\TriangleTest - TriangleForces.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Jun-2019 12:30:18

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Sample", "ForceX", "ForceY", "ForceZ", "COPx", "COPy", "VarName7"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 7, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 7, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
TriangleTestTriangleForces = readtable(filename, opts);

end