function forceData = importForces(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DUALDIALSKATER1TRIANGLEFORCES = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  DUALDIALSKATER1TRIANGLEFORCES = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  dualdialskater1TriangleForces = importfile("C:\Users\Daniel.Feeney\Dropbox (Boa)\AgilityPerformance\NB Hierro\dualdial skater 1 - TriangleForces.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Nov-2019 11:18:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 22);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Sample", "RForceX", "RForceY", "RForceZ", "RCOPx", "RCOPy", "LForceX", "LForceY", "LForceZ", "LCOPx", "LCOPy", "RForceX2", "RForceY2", "RForceZ2", "RCOPx2", "RCOPy2", "LForceX2", "LForceY2", "LForceZ2", "LCOPx2", "LCOPy2", "VarName22"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 22, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 22, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
forceData = readtable(filename, opts);

end