function TriangleTestTriangleKinetics = importKinetics(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TRIANGLETESTTRIANGLEKINETICS = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the data as a
%  table.
%
%  TRIANGLETESTTRIANGLEKINETICS = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  TriangleTestTriangleKinetics = importfile("C:\Users\Daniel.Feeney\Dropbox (Boa)\TMM Files\TriangleTest - TriangleKinetics.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 24-Jun-2019 12:41:42

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Sample", "COMPower", "Landing", "Takeoff", "LAnklePower", "RAnklePower", "COMPower1", "VarName8"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "string"];
opts = setvaropts(opts, 8, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 8, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
TriangleTestTriangleKinetics = readtable(filename, opts);

end